### ISSUE TITLE
glibc programs crash if executable path is not absolute

### ISSUE THREAD

**Issue by jrprice** [UoB-HPC/SimEng#125]
Some programs linked against glibc will crash if they are passed to SimEng with relative paths. I suspect we just need to canonicalise the path during the `readlinkat` syscall, since glibc checks the first character to see if starts with `/`. The crash looks like this:

```
$ ./bin/simeng emulation ./triad-glibc-printf
Running in Emulation mode
Starting...
../sysdeps/unix/sysv/linux/generic/dl-origin.c:48: _dl_get_origin: Assertion `linkval[0] == '/'' failed.

<then hits an svc we don't yet implement>
```
(note that the assertion failure is coming from an assertion inside glibc in the emulated program, not an assertion inside SimEng).

**Comment by FinnWilkinson** [comment]
Fixed with PR #379 merged into `dev`
