### ISSUE TITLE
Regression test CMake target does not depend on executable

### ISSUE THREAD

**Issue by jrprice** [UoB-HPC/SimEng#130]
Running `make test` doesn't automatically rebuild the regression test executables themselves if their sources have changed. One currently has to run `make && make test` to ensure this is done if working on the regression tests.

There's probably a way to do this in CMake, but I couldn't work it out at quick skim (sorry!).

**Comment by FinnWilkinson** [comment]
This issue was solved in #169 with the addition of the `test-all` target
