### ISSUE TITLE
Running binaries from different Operating Systems

### ISSUE THREAD

**Issue by jj16791** [UoB-HPC/SimEng#180]
SimEng should be able to support codes compiled across a variety of commonly used operating systems (RHEL, CentOS, macOS, Windows, Ubuntu, etc), and in turn their libraries. Recent unexpected behaviour concerning the calling of `mmap` system call on RHEL and CentOS has meant simple programs compiled on these systems cannot currently be simulated by SimEng.

A way to create these binaries must be set up and developments to fix the lacking support must be carried out.

**Comment by FinnWilkinson** [comment]
Given recent changes made in `multi-thread-support` branch which solidifies our implementation of MMAP syscall, and the general improvement of our Linux ELF and syscall emulation found in release 0.9.5, I propose closing this issue and instead opening two/three new issues titled "Support dynamically linked binaries", "Support Mach-O binaries", and "Support EXE binaries" (the latter only if we still want to add support for Windows compiled executables, which, given we do not support running SimEng on Windows currently may not be within scope). 

Given how different each of these three tasks are, splitting this issue up makes each goal more achievable in my opinion.

**Comment by jj16791** [comment]
Agreed, this older issue is best split into the recommended newer issues which better align with recent developments. Currently, there's no active plan for supporting Windows or its executables so I think it's best left out for now and reconsidered in the future.

**Comment by FinnWilkinson** [comment]
Closing this issue based on the above, and opening two new issues for Dynamic linking support and Mach-O executable support
