### ISSUE TITLE
Cannot run CloverLeaf Serial and OpenMP

### ISSUE THREAD

**Issue by TasteDaBombDev** [UoB-HPC/SimEng#213]
I have tried to run the CloverLeaf OpenMP application on my custom made RISC V architecture and it displays the following output: https://pastebin.com/yd6rJurh

-- Backgorund Information --
All the files are in ~/SimEng,  ~/CloverLeaf_OpenMP, ~/SimEng/install/bin/ ( for the simeng app ).
The cloverleaf applications I have installed using their documentation and my running the command: 

`make COMPILER=GNU MPI_COMPILER=gfortran C_MPI_COMPILER=gcc`

as seen here: https://github.com/UK-MAC/CloverLeaf_OpenMP

This is my GNU version: Linux version 5.11.0-36-generic (buildd@lcy01-amd64-004) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #40~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021

**Comment by jj16791** [comment]
Could you provide a file containing the assembly of the binary used here (e.g. `objdump -d <binary> > <output>`)

**Comment by jj16791** [comment]
I have a feeling it may be a problem to do with instruction aliasing

**Comment by TasteDaBombDev** [comment]
[output.txt](https://github.com/UoB-HPC/SimEng/files/8048826/output.txt)
This is the output from the binary I have used there. Many thanks

**Comment by jj16791** [comment]
> [output.txt](https://github.com/UoB-HPC/SimEng/files/8048826/output.txt) This is the output from the binary I have used there. Many thanks

This is X86 assembly that won't run through SimEng because we don't yet support it (we only officially support a subsection of the armv8 ISA).

**Comment by TasteDaBombDev** [comment]
Thanks for the feedback. If I manage to run the RISC V on an arm machine, will be able to run any binaries, then?

**Comment by jj16791** [comment]
> Thanks for the feedback. If I manage to run the RISC V on an arm machine, will be able to run any binaries, then?

Unless you've added support for another ISA personally, you will need a binary compiled for the armv8 ISA. SimEng will then be able to process the workload for simulation. You may still come across errors where we have yet to support a specific instruction in the armv8 ISA but hopefully, this shouldn't be common.
