### ISSUE TITLE
Instruction trace

### ISSUE THREAD

**Issue by youpeng326** [UoB-HPC/SimEng#276]
In the slides there is an instruction trace window which shows the cycles and assembly. How to get this ?

**Comment by jj16791** [comment]
@youpeng326 Thank you for your interest in the tracing tool. The trace viewer utility can be found at https://github.com/jj16791/ACA-tracer. The input file for the tracer tool can either be generated manually or use the [trace](https://github.com/UoB-HPC/SimEng/tree/trace) branch as a starting point. It's currently not updated with the latest developments in `main` but we're looking to find a solution to get the tracing support into our mainline developments.

**Comment by FinnWilkinson** [comment]
Closing issue as stale

**Comment by elfmath** [comment]
Hello, thank you for the trace's support. As a user of the simulator it is very useful. Is there a feature to trace the value of GP registers at each instruction yet ? in the same way as GDB or Trace32 when debugging step-by-step ?
