### ISSUE TITLE
Can't not run SME code on SimEng

### ISSUE THREAD

**Issue by HKLee2040** [UoB-HPC/SimEng#281]
According to "An Initial Evaluation of Arm’s Scalable Matrix Extension", I try to duplicate the result.

I can compile SVE/SME evaluation codes successfully, but it's Armclang 22.1. (I can't find 22.0.2 now)
But when I try to simulate the binary code by SimEng, it shows me the following error:
$ ./simeng a64fx.yaml sve_matmul_fp32 iterations 128 128 128

../sysdeps/unix/sysv/linux/generic/dl-origin.c:48: _dl_get_origin: Assertion `linkval[0] == '/'' failed.

Do I miss anything? Would you please help me to solve it? How can I duplicate your result?

I meet the same problem when I used both LLVM_SME_changes and SME_PR  branch.

**Comment by FinnWilkinson** [comment]
Hi, from the sounds of things you are building the binaries dynamically which isn't currently supported in the simulator. Please try again after compiling them with the `--static` flag. 

Our SME support hasn't been merged into main branch yet, so I would recommend using the `dev` branch at the moment.

Also, I notice that the input arguments for the MatMul binaries isn't quite correct; you need to include the number of iterations as the first argument (i.e. `sve_matmul_fp32 200 128 128 128` for 200 iterations), otherwise the binary will default to a 128x128x128 input size.

**Comment by HKLee2040** [comment]
I had used dev branch and used the following command to compile the code:
armclang -static -march=armv8.4-a+sve -Wall -O3 -o sve_matmul_fp32 main.c matmul.c

But still met the same problem:

[SimEng] Build metadata:
[SimEng]        Version: 0.9.4
[SimEng]        Compile Time - Date: 12:52:37 - Dec 26 2022
[SimEng]        Build type: Release
[SimEng]        Compile options: -Wall;$<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
[SimEng]        Test suite: ON

[SimEng] Running in Out-of-Order mode
[SimEng] Workload: sve_matmul_fp32 200 128 128 128
[SimEng] Config file: a64fx.yaml
[SimEng] Starting...

../sysdeps/unix/sysv/linux/generic/dl-origin.c:48: _dl_get_origin: Assertion `linkval[0] == '/'' failed.

[SimEng:ExceptionHandler] Received exit_group syscall: terminating with exit code 127
[SimEng:Core] Halting due to fatal exception

[SimEng] branch.executed: 2394
[SimEng] branch.mispredict: 832
[SimEng] branch.missrate: 34.8%
[SimEng] cycles: 10725
[SimEng] decode.earlyFlushes: 0
[SimEng] dispatch.rsStalls: 42
[SimEng] fetch.branchStalls: 3774
[SimEng] flushes: 871
[SimEng] ipc: 0.75
[SimEng] issue.backendStalls: 659
[SimEng] issue.frontendStalls: 1952
[SimEng] issue.portBusyStalls: 108
[SimEng] lsq.loadViolations: 46
[SimEng] rename.allocationStalls: 1
[SimEng] rename.lqStalls: 0
[SimEng] rename.robStalls: 4
[SimEng] rename.sqStalls: 24
[SimEng] retired: 8067

[SimEng] Finished 10725 ticks in 40ms (268 kHz, 0.2 MIPS)

**Comment by FinnWilkinson** [comment]
Please could you run `file sve_matmul_fp32` and post the output?

Also when running SimEng, please make sure you use the binary file's full file path
i.e. `./simeng a64fx.yaml /home/user/FILE/PATH/sve_matmul_fp32 200 128 128 128`

**Comment by HKLee2040** [comment]
The output is shown as below:
(QEMU environment by ubuntu-18.04-server-arm64.iso, ARM compiler version 22.1)

rogers@ubuntu:~/SME_Evaluation_Resources/SVE_matmul_fp32$ ./sve_matmul_fp32 200 128 128 128
Left Matrix Dimensions = 128 x 128
Right Matrix Dimensions = 128 x 128
SVE Loop iterations = 200

Calculating Reference Matrix Multiply...
Done
Calculating 200 iterations of SVE Matrix Multiply...
Done

ERROR TOLERANCE = 0.0002%
PASS

**And the SimEng is "dev" branch**

(py36) rogers@atcarch01:/local/work/ARM_SME$ /local/work/ARM_SME/Sim/bin/simeng a64fx.yaml sve_matmul_fp32 200 128 128 128
[SimEng] Build metadata:
[SimEng]        Version: 0.9.4
[SimEng]        Compile Time - Date: 09:48:39 - Dec 31 2022
[SimEng]        Build type: Release
[SimEng]        Compile options: -Wall;$<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
[SimEng]        Test suite: ON

[SimEng] Running in Out-of-Order mode
[SimEng] Workload: sve_matmul_fp32 200 128 128 128
[SimEng] Config file: a64fx.yaml
[SimEng] Starting...

../sysdeps/unix/sysv/linux/generic/dl-origin.c:48: _dl_get_origin: Assertion `linkval[0] == '/'' failed.

[SimEng:ExceptionHandler] Received exit_group syscall: terminating with exit code 127
[SimEng:Core] Halting due to fatal exception

[SimEng] branch.executed: 2394
[SimEng] branch.mispredict: 832
[SimEng] branch.missrate: 34.8%
[SimEng] cycles: 10725
[SimEng] decode.earlyFlushes: 0
[SimEng] dispatch.rsStalls: 42
[SimEng] fetch.branchStalls: 3774
[SimEng] flushes: 871
[SimEng] ipc: 0.75
[SimEng] issue.backendStalls: 659
[SimEng] issue.frontendStalls: 1952
[SimEng] issue.portBusyStalls: 108
[SimEng] lsq.loadViolations: 46
[SimEng] rename.allocationStalls: 1
[SimEng] rename.lqStalls: 0
[SimEng] rename.robStalls: 4
[SimEng] rename.sqStalls: 24
[SimEng] retired: 8067

[SimEng] Finished 10725 ticks in 40ms (268 kHz, 0.2 MIPS)

**Comment by FinnWilkinson** [comment]
I can see that you are still not executing SimEng quite right. Please provide SimEng the **_full path_** to the binary you wish to run as follows :

`./simeng a64fx.yaml /local/work/ARM_SME/sve_matmul_fp32 200 128 128 128`

**Comment by HKLee2040** [comment]
Sorry, I misunderstood the full path meaning.
Now, it work pretty good.  Thanks for your help.

**Comment by HKLee2040** [comment]
Sorry, I met another issue while I try to test SME code.  It seems that zero {za} can't be recognized.  Is it normal?

(py36) rogers@atcarch01:/local/work/ARM_SME$ ./Sim/bin/simeng a64fx.yaml /local/work/ARM_SME/sme_matmul_fp32 10 128 128 128
[SimEng] Build metadata:
[SimEng]        Version: 0.9.4
[SimEng]        Compile Time - Date: 13:18:33 - Jan  6 2023
[SimEng]        Build type: Release
[SimEng]        Compile options: -Wall;$<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
[SimEng]        Test suite: ON

[SimEng] Running in Out-of-Order mode
[SimEng] Workload: /local/work/ARM_SME/sme_matmul_fp32 10 128 128 128
[SimEng] Config file: a64fx.yaml
[SimEng] Starting...

Left Matrix Dimensions = 128 x 128
Right Matrix Dimensions = 128 x 128
SME Loop iterations = 10

Calculating Reference Matrix Multiply...
Done
Calculating 10 iterations of SME Matrix Multiply...

[SimEng:ExceptionHandler] Encountered unsupported execution port exception
[SimEng:ExceptionHandler]   Generated by instruction:
[SimEng:ExceptionHandler]     0x0000000000400ad8: ff 00 08 c0     zero {za}
[SimEng:ExceptionHandler]       opcode ID: 6306
[SimEng:Core] Halting due to fatal exception

[SimEng] branch.executed: 940354
[SimEng] branch.mispredict: 144950
[SimEng] branch.missrate: 15.4%
[SimEng] cycles: 4018548
[SimEng] decode.earlyFlushes: 0
[SimEng] dispatch.rsStalls: 228413
[SimEng] fetch.branchStalls: 1223695
[SimEng] flushes: 273670
[SimEng] ipc: 1.2
[SimEng] issue.backendStalls: 628847
[SimEng] issue.frontendStalls: 222357
[SimEng] issue.portBusyStalls: 40892
[SimEng] lsq.loadViolations: 128758
[SimEng] rename.allocationStalls: 352959
[SimEng] rename.lqStalls: 0
[SimEng] rename.robStalls: 46436
[SimEng] rename.sqStalls: 30
[SimEng] retired: 4963884

[SimEng] Finished 4018548 ticks in 11354ms (354 kHz, 0.44 MIPS)

**Comment by HKLee2040** [comment]
Thanks for your information.  It works now.
