### ISSUE TITLE
Clean Up / Replace CoreInstance.cc

### ISSUE THREAD

**Issue by FinnWilkinson** [UoB-HPC/SimEng#358]
The `CoreInstance` class was a biproduct of integrating SST with SimEng, largely due to the linking issues SST has with YAML.cpp. With the completion of Item [#1](https://github.com/orgs/UoB-HPC/projects/1/views/1?pane=issue&itemId=43466264), this class can be removed and the logic it contains can be moved to a factory style function.

**Comment by jj16791** [comment]
Closing as the raised issue does represent the full intent/usage of `CoreInstance` and upcoming developments will most likely see its removal.
