### ISSUE TITLE
Interface-Type restriction not applied

### ISSUE THREAD

**Issue by jj16791** [UoB-HPC/SimEng#372]
Both `L1-Data-Memory` and `L1-Instruction-Memory` `Interface-Type` option has restrictions possibly based on the `Simulation-Mode` in use. Namely, only a `Flat` value can be used for `L1-Instruction-Memory` and only a non-`Flat` `L1-Data-Memory` value can be used if the `Simulation-Mode` is set to be `outoforder`.

Additionally, the outoforder tests in the regression test suite should use a `Fixed` `L1-Data-Memory` for a more realistic testing scenario.

**Comment by FinnWilkinson** [comment]
Closing issue due to fix being merged into `dev`
