### ISSUE TITLE
AArch64 ST1W test failure due to dirty page usage

### ISSUE THREAD

**Issue by jj16791** [UoB-HPC/SimEng#382]
When recreating ELF process images within one test case (e.g. `AArch64/InstSve.st1w/emulationWithVL128`), an error can be exposed when reading malloced memory that hasn't been written to yet.

This behaviour is exposed in the `AArch64/InstSve.st1w/emulationWithVL*` test cases where a st1w with half active and half inactive lanes expects zero memory values in the memory locations with associated inactive lanes. However, due to prior `RUN_AARCH64` instances within the test case and the reuse of dirtied (previously written to) pages given to the `char* unwrappedProcImgPtr = (char*)malloc(size_, sizeof(char));` malloc call, those memory locations are consistently non-zero and thus the `EXPECT_EQ` calls will fail.

**Comment by FinnWilkinson** [comment]
Fix in `dev` as of PR #383
